---
language: python
python: "3.7"

branches:
  only:
  - master
  - /^v\d/

notifications:
  email:
    on_success: never
    on_failure: always

services:
- docker

install:
- pip install ansible

script:
- travis_wait 30 tests/run_playbook.sh
