- name: make sure base directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  loop:
  - "{{ ood_base_apache_dir }}"
  - "{{ ood_app_dir }}"
  - "{{ ood_sys_app_dir }}"
  - "{{ ood_dev_app_dir }}"
  - "{{ ood_usr_app_dir }}"
  - "{{ ood_base_dir }}"
  - "{{ ood_base_apache_dir }}/public"
  - "{{ ood_base_apache_dir }}/discover"
  - "{{ ood_base_conf_dir }}"

- name: make os directories when required
  file:
    path: "{{ item }}"
    state: directory
  become: true
  loop: "{{ os_directories }}"
  when: os_directories is defined

- name: move apps to their directories
  copy:
    src: "{{ ood_source_dir }}/build/apps/{{ item }}"
    dest: "{{ ood_sys_app_dir }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: true
  loop: "{{ ood_base_apps }}"

- name: move core libs to their directories
  copy:
    src: "{{ ood_source_dir }}/{{ item }}"
    dest: "{{ ood_base_dir }}"
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: true
  loop: "{{ ood_core_libs }}"

- name: make nginx config files for core sys apps
  file:
    path: "{{ nginx_apps_dir }}/sys/{{ item }}.conf"
    state: touch
    owner: root
    group: root
    mode: '0644'
  become: true
  loop: "{{ ood_base_apps }}"

- name: make version file
  copy:
    content: "{{ ood_source_version }}"
    dest: "{{ ood_base_dir }}/VERSION"
  become: true

- name: cleanup build logfiles
  file:
    path: "{{ ood_sys_app_dir }}/log/production.log"
    state: absent
  become: true
  loop: "{{ ood_base_apps }}"

- name: give the apache user rights to nginx_stage
  template:
    src: ood-sudoers.j2
    dest: /etc/sudoers.d/ood
  become: true
