---
- name: restart apache in systemd
  systemd:
    name: "{{ apache_service_name }}"
    state: restarted
    enabled: "{{ apache_service_enabled }}"
  become: true
  when: ansible_connection == "ssh" or ansible_connection == "local"
  listen: "restart apache httpd"

- name: restart apache in container
  shell: "{{ container_apache_restart_cmd }}"
  become: true
  when: ansible_connection == "podman" or ansible_connection == "docker"
  listen: "restart apache httpd"

- name: update nginx stage
  shell: "{{ ood_base_dir }}/nginx_stage/sbin/update_nginx_stage"
  become: true
