# custom ood_portal.yml configurations
host_regex: 'forge-(l|c)\d+'
user_map_cmd: '/opt/ood/ood_auth_map/bin/ood_auth_map.regex --regex=''''^([A-Za-z0-9\-_\.]+)@osc.edu$'''''
rnode_uri: '/custom-rnode-path'
node_uri: '/custom-node-path'
oidc_uri: '/custom-oidc-path'

ood_auth_openidc:
  OIDCSessionMaxDuration: 28888
  OIDCClientID: myid
  OIDCProviderMetadataURL: https://localhost/
  OIDCCryptoPassphrase: mycryptopass