---
- name: Converge
  hosts: instance
  roles:
    - role: ood-ansible
      ood_portal_generator: false

- name: Custom
  hosts: custom
  roles:
    - role: ood-ansible
  vars_files:
    - vars/custom.yml

- hosts: all
  tasks:
    - name: create ood user
      user:
        name: ood
    - name: create debug user apache auth user ood:ood
      copy:
        content: 'ood:$apr1$EOza4zZK$fuKLibf.WGN2E5MuovgQs.'
        dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
