---
- name: Converge
  hosts: instance
  roles:
    - role: ood-ansible
      install_from_src: false
      apache_service_enabled: true
      _container_connection: false
      _ssh_local_connection: true

- name: Custom
  hosts: custom
  roles:
    - role: ood-ansible
      install_from_src: false
      apache_service_enabled: true
      ood_portal_generator: true
      nginx_min_uid: 500
      _container_connection: false
      _ssh_local_connection: true

- hosts: all
  tasks:
    - name: create ood user
      user:
        name: ood
    - name: create debug user apache auth user ood:ood
      copy:
        content: 'ood:$apr1$EOza4zZK$fuKLibf.WGN2E5MuovgQs.'
        dest: /opt/rh/httpd24/root/etc/httpd/.htpasswd
